### ISSUE TITLE
Feature suggestion: body classes for given consents

### ISSUE THREAD

**Issue by artfulrobot** [blaueQuelle/privacywire#39]
I would find it useful to update the `<body>` element with classes like `consent-marketing` if/when that consent has been given.

The reason for this is that then I can use CSS like

```css
body.consent-marketing .hide-if-marketing-consent-given { display:none; }
body:not(.consent-marketing) .show-if-marketing-consent-given { display:none; }
```

And HTML like 

```html
<p class="hide-if-marketing-consent-given">Some alternative rendering of the content that wants consent.</p>
<p class="show-if-marketing-consent-given">Sucker!</p>
```

I'm happy to implement this (and happy to either add a 2nd PR or add it to #38) if it would be welcome?
